trigger:
  branches:
    include:
      - master

pool:
  name: Default

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.10.0  # Specify the Python version you want to use
    addToPath: true

- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python app.py
  displayName: 'Run Flask application'

