trigger:
  branches:
    include:
      - master

pool:
  name: Default

steps:
- script: |
    echo "Hello, Azure DevOps!"
    python -m venv env
    .\env\Scripts\activate
    python -m pip install --upgrade pip
    echo installed pip
    pip install -r requirements.txt
    echo installed reqs
    python app.py
    echo running flask
  displayName: 'Print Message'
