trigger:
  branches:
    include:
      - master

pool:
  name: Default

steps:
- script: |
    echo "Hello, Azure DevOps!"
    pip install -r requirements.txt
    python app.py
  displayName: 'Print Message'
