trigger:
  branches:
    include:
      - master

pool:
  name: Default

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.10.0  # Specify the Python version you want to use
    addToPath: true

- script: |
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python app.py
  displayName: 'Run Flask application'

trigger:
  branches:
    include:
      - master

pool:
   name:Default
steps:
- script: |
    python --version
    python -m venv env
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Setup Python environment'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'app.py'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy app.py'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
  displayName: 'Archive app.py'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/app.zip'
    ArtifactName: 'FlaskApp'
    publishLocation: 'Container'
  displayName: 'Publish Flask App artifact'

- script: |
    echo 'Deploying Flask App...'
    # Add deployment steps here
  displayName: 'Deploy Flask App'
