trigger:
  branches:
    include:
      - master

pool:
  name: Default

steps:
- script: |
    echo "Hello, Azure DevOps!"
    python -m venv env
    .\env\Scripts\activate
    python -m pip install --upgrade pip
    pip install -r requirements.txt
    python -m flask run
  displayName: 'Print Message'
