trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - '*'

pool:
  name: Default
  demands:
  - agent.name -equals vikas

variables:
  - name: FLASK_APP
    value: 'app.py'
  - name: FLASK_ENV
    value: 'production'

steps:
- script: |
    
    python --version
    pip install --upgrade pip
    pip install -r requirements.txt
    flask run
  displayName: 'Run Flask application'
