trigger:
  branches:
    include:
      - master

pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'ubuntu-latest'

variables:
  - name: FLASK_APP
    value: 'app.py'
  - name: FLASK_ENV
    value: 'production'

steps:
- script: |
    python -m venv env
    source env/bin/activate
    pip install --upgrade pip
    pip install -r requirements.txt
    flask run
  displayName: 'Run Flask application'
