trigger:
  branches:
    include:
      - master

pool:
  name: Default

steps:
- script: |
    python --version
    python -m venv env
    pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Setup Python environment'

- script: |
    echo 'Deploying Flask App...'
    python app.py
  displayName: 'Deploy Flask App'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '663de6ca-2c5f-43fb-8b49-32df23affad7'
    appName: 'myWebApp66099'
    package: '$(Build.SourcesDirectory)'
    deployToSlotOrASE: false
    resourceGroupName: 'demo_rgx'
  displayName: 'Deploy to Azure Web App'
